Cloudflare:
  Email: [your cloudflare email]
  API: [your cloudflare global api key]
  Zone: [your domain zone id]
  Domain: [your domain / subdomain]
  Gen: true

Nodes:
  API: [your panel url]
  Token: [your panel token]
  Panel: [your panel type]
